### ISSUE TITLE
Dependencies differences 

### ISSUE THREAD

**Issue by Ludocius** [cescoffier/reactive-systems-in-java#237]
Hello mr. @cescoffier
I'm currently reading your book and found out this following problem:
 
Please update these dependencies due to differences in **quarkus** version and **quarkus** platform
<img width="515" alt="image" src="https://github.com/cescoffier/reactive-systems-in-java/assets/59232095/40ddb550-a433-4d69-97b9-629364f65184">
leading to dependencies problems when running the application
<img width="922" alt="image" src="https://github.com/cescoffier/reactive-systems-in-java/assets/59232095/f2f1699d-f18e-4907-b46e-3be5188b142d">

**Comment by cescoffier** [comment]
Which file is it?

**Comment by Ludocius** [comment]
At the moment of the commentary on package chapter 8
<img width="192" alt="image" src="https://github.com/cescoffier/reactive-systems-in-java/assets/59232095/7cb0cb3c-3449-494a-aaca-8132f86a4007">
